# Sample configuration for thaumiel

[app]

# Logging level for the web server. If empty defaults to info.
log-level = "debug"

[network]

# What hostname the server uses.
hostname = "thaumiel"

# Whether to use IPv6 or not.
use-ipv6 = true

# What port to serve on.
port = 8000

# The keep-alive duration in seconds. Use 0 to disable.
keep-alive = 65

[files]

# What directory to fetch static files from
static-dir = "/var/www/static"

[deepwell]

# IP address or hostname to connect to
host = "localhost"

# What port the server is hosted on
port = 2747
