# Sample configuration for kant-router

[app]

# Logging level for the web server. If empty defaults to info.
log-level = "debug"

[network]

# What hostname the server uses.
hostname = "kant"

# Whether to use IPv6 or not.
use-ipv6 = true

# What port to serve on.
port = 8000

# The keep-alive duration in seconds. Use 0 to disable.
keep-alive = 65
