# Sample configuration for thaumiel

[app]

# Logging level for the web server. If empty defaults to info.
log-level = "debug"

[network]

# What hostname the server uses.
hostname = "thaumiel"

# Whether to use IPv6 or not.
use-ipv6 = true

# What port to serve on.
port = 8000

# The keep-alive duration in seconds. Use 0 to disable.
keep-alive = 65

[security]

# Whether the cookie should be HTTP-only (false) or HTTPS-only (true).
# This should be set when in production! It should only be false for local testing!
cookie-secure = false

# How long a cookie lives, in seconds.
# This setting cannot be disabled; if you want sessions to exist
# for a long time, set this to a high number.
cookie-max-age = 604800

# The same-site policy for cookies.
# Can either be "strict", "lax", or "none".
cookie-same-site = "strict"

# Where to find the session key for encrypting cookies.
# Must be at least 32 bytes.
cookie-key-path = "thaumiel-cookie.key"

[files]

# What directory to fetch static files from.
static-dir = "/var/www/static"

[deepwell]

# IP address or hostname to connect to.
host = "localhost"

# What port the server is hosted on.
port = 2747
