# Sample configuration for kant-router

[app]

# Logging level for the web server. If empty defaults to info.
log-level = "debug"

[network]

# What hostname the server uses.
hostname = "kant"

# Whether to use IPv6 or not.
use-ipv6 = true

# What port to serve HTTP/HTTPS on.
http-port = 8000
https-port = 8443

[ssl]
private-key-file = "misc/test-private-key.pem"
certificate-file = "misc/test-certificate.pem"

[forwards]

# What directory to get static file requests from.
file = "/var/www"

# Where to send page requests.
page = "http://localhost:7243"
