language: rust
rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx
  - windows

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

cache: cargo

before_script:
  - rustup component add rustfmt

stages:
  - format
  - clippy
  - test

jobs:
  include:
    - stage: format
      script:
        - rustfmt --edition=2018 --check src/main.rs
    - stage: clippy
      script:
        - rustup toolchain install nightly-2020-01-02-x86_64-unknown-linux-gnu
        - rustup component add clippy --toolchain nightly-2020-01-02-x86_64-unknown-linux-gnu
        - cargo +nightly-2020-01-02 clippy
    - stage: test
      rust:
        - stable
        - beta
        - nightly
      os:
        - linux
        - osx
        - windows
      script:
        - cargo build --verbose
        - cargo test --verbose -- --nocapture

notifications:
  email:
    on_success: change
    on_failure: always
