language: rust
rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx
  - windows

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

cache: cargo

before_script:
  - rustup component add rustfmt

stages:
  - format
  - test

jobs:
  include:
    - stage: format
      script:
        - rustfmt src/main.rs --check
    - stage: test
      rust:
        - stable
        - beta
        - nightly
      os:
        - linux
        - osx
        - windows
      script:
        - cargo build --verbose
        - cargo test --verbose -- --nocapture

notifications:
  email:
    on_success: change
    on_failure: always
