[package]
name = "kant-router"
description = "A Wikidot-compatible router for web applications"
repository = "https://github.com/Nu-SCPTheme/kant-router"
readme = "README.md"
license = "AGPL-3.0-or-later"
keywords = ["wikidot", "router", "web", "nuscp"]
categories = ["web-programming::http-server"]
exclude = [".gitignore", ".travis.yml"]

version = "0.0.6"
authors = ["Ammon Smith <ammon.i.smith@gmail.com>"]
edition = "2018" # this refers to the Cargo.toml version

[dependencies]
actix-web = { version = "1", features = ["client", "rust-tls"] }
color-backtrace = "0.2"
futures = "*"
lazy_static = "1"
log = "0.4"
maplit = "1"
rustls = "0.15"
percent-encoding = "2"
pretty_env_logger = "0.3"
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
str-macro = "0.1"
structopt = "0.3"
toml = "0.5"
