[package]
name = "kant-router"
version = "0.0.1"
authors = ["Ammon Smith <ammon.i.smith@gmail.com>"]
edition = "2018" # this refers to the Cargo.toml version

[dependencies]
actix-web = "1"
awc = "*"
color-backtrace = "0.2"
futures = "*"
lazy_static = "1"
log = "0.4"
maplit = "1"
percent-encoding = "2"
pretty_env_logger = "0.3"
regex = "1"
serde = { version = "1", features = ["derive"] }
str-macro = "0.1"
structopt = "0.3"
toml = "0.5"
